spring.application.name=api-gateway-service
server.port=8000
#Eureka config

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webflux.discovery.locator.enabled=false


#Define static routers for product service
spring.cloud.gateway.server.webflux.routes[0].id=product.service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/products/**


#Define static routers for order service
spring.cloud.gateway.server.webflux.routes[1].id=order.service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**




